"use client";

import { useState } from "react";
import { strategies, StrategyKey } from "../../data";
import Hero from "../../components/Hero";
import TabsNav from "../../components/TabsNav";
import HighLevelTab from "../../components/HighLevelTab";
import TradeDataTab from "../../components/TradeDataTab";
import CompareTab from "../../components/CompareTab";
import DownloadsTab from "../../components/DownloadsTab";

type Tab = "high-level" | "trade-data" | "compare" | "downloads";

export default function StrategyPage({ params }: { params: { id: string } }) {
  const strategyKey = (params.id === "sigma-1x" || params.id === "sigma-2x")
    ? params.id as StrategyKey
    : "sigma-1x" as StrategyKey;

  const [activeTab, setActiveTab] = useState<Tab>("high-level");
  const s = strategies[strategyKey];

  return (
    <main className="min-h-screen bg-[#f5f5f7]">
      <Hero strategyKey={strategyKey} />

      {/* Strategy name + Decrypt branding + description */}
      <div className="max-w-5xl mx-auto px-6 pt-8 pb-4">
        <div className="flex items-center gap-3 mb-3">
          <h2 className="text-xl font-bold text-gray-900">{s.name}</h2>
          <span className="text-gray-300">|</span>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/decrypt-white-bg.svg"
            alt="Decrypt Capital"
            className="w-[160px]"
          />
        </div>
        <p className="text-sm text-gray-500 leading-relaxed max-w-3xl">
          {s.description}
        </p>
      </div>

      {/* Tabs */}
      <div className="max-w-5xl mx-auto px-6">
        <TabsNav activeTab={activeTab} onSwitch={setActiveTab} />

        <div className="mt-6 pb-20">
          {activeTab === "high-level" && <HighLevelTab strategyKey={strategyKey} />}
          {activeTab === "trade-data" && <TradeDataTab strategyKey={strategyKey} />}
          {activeTab === "compare" && <CompareTab strategyKey={strategyKey} />}
          {activeTab === "downloads" && <DownloadsTab strategyKey={strategyKey} />}
        </div>
      </div>

      {/* Disclaimer */}
      <div className="max-w-5xl mx-auto px-6 pb-10">
        <div className="border-t border-gray-200 pt-6">
          <p className="text-[11px] text-gray-400 leading-relaxed">
            <strong className="text-gray-500">Disclaimer:</strong> All data shown is from backtesting.
            Past performance does not guarantee future returns. Paper trading active since March 7, 2026.
            Presentations and media content are generated by Notebook LM, a Google product.
            For detailed analysis, please refer to the data and documentation files available in the Downloads section.
          </p>
        </div>
      </div>
    </main>
  );
}
