export const strategies = {
  "sigma-1x": {
    id: "sigma-1x",
    name: "Sigma 1x",
    tagline: "Spot Trading — Long Only — Profit in USD",
    description:
      "Automated spot trading bot. Buys dips and takes small profits across 5 coins with no leverage. Long only — holds coins and profits in USD. Zero liquidation risk.",
    type: "DCA (Buy the Dip)",
    direction: "Long only",
    leverage: "None (1x spot)",
    market: "Spot",
    liquidationRisk: "Zero",
    coins: ["DOGE", "ADA", "XRP", "ETH", "SOL"],
    timeframe: "1-hour candles",
    backtestPeriod: "2019–2026 (6.7 years)",
    allYearsProfitable: true,
    status: "Paper Trading (since Mar 7, 2026)",
    recommendedCapital: "$10,000+",
    stats: {
      winRate: "94–99%",
      sharpe: "2.41–3.31 (avg 2.81)",
      maxDrawdown: "2.8–6.9%",
      profitFactor: "2.26–7.45",
      totalTrades: "~25,000+",
    },
    perCoin: [
      { coin: "DOGE", totalReturn: "+228.6%", maxDD: "2.8%", sharpe: "2.59", winRate: "97.1%", profitFactor: "3.72" },
      { coin: "ADA", totalReturn: "+211.1%", maxDD: "6.9%", sharpe: "2.81", winRate: "98.2%", profitFactor: "5.27" },
      { coin: "XRP", totalReturn: "+265.4%", maxDD: "3.2%", sharpe: "3.31", winRate: "99.4%", profitFactor: "7.45" },
      { coin: "ETH", totalReturn: "+88.3%", maxDD: "3.7%", sharpe: "2.41", winRate: "94.4%", profitFactor: "2.26" },
      { coin: "SOL", totalReturn: "+115.8%", maxDD: "3.2%", sharpe: "2.95", winRate: "96.3%", profitFactor: "2.71" },
    ],
    liveData: {
      pnl30d: "—",
      trades30d: "—",
      amountTrading: "—",
      minFunds: "$10,000 / 0.1 BTC",
    },
    backtestBars: [
      { label: "80m (6.7yr)", value: "+265.4%", barPercent: 95 },
      { label: "36m",         value: "+181.8%", barPercent: 70 },
      { label: "12m",         value: "+42.5%",  barPercent: 40 },
      { label: "6m",          value: "+18.2%",  barPercent: 25 },
    ],
    media: {
      explainer: "https://kwtagyeqhdxswpztqcsa.supabase.co/storage/v1/object/public/data-room/media/sigma-1x-explainer.mp4",
      pitch: "https://kwtagyeqhdxswpztqcsa.supabase.co/storage/v1/object/public/data-room/media/sigma-1x-pitch.pdf",
    },
    safetyLayers: [
      { name: "Per-trade stop-loss", desc: "Hard maximum loss on every trade" },
      { name: "4-confirmation entry", desc: "Trend, momentum, volatility & cooldown must all pass" },
      { name: "Capital limits", desc: "Reserve always held back; no coin uses more than 25%" },
      { name: "Circuit breakers", desc: "Auto-reduce → pause → full halt on daily/weekly/monthly losses" },
      { name: "Manual kill switch", desc: "Instant shutdown from the dashboard" },
    ],
  },
  "sigma-2x": {
    id: "sigma-2x",
    name: "Sigma 2x",
    tagline: "Derivatives Trading — Long & Short — Inverse Futures",
    description:
      "Fully systematic derivatives strategy on inverse futures. 2x leveraged, bidirectional — goes long in bull markets and short in bear markets. Holds position and profits in USD via regime detection.",
    type: "Systematic DCA + Regime Detection",
    direction: "Bidirectional (long + short)",
    leverage: "2x (isolated margin)",
    market: "Derivatives (Inverse Futures)",
    liquidationRisk: "Zero liquidations in 4.2yr backtest",
    coins: ["DOGE", "ADA", "XRP", "ETH", "SOL"],
    timeframe: "1-hour candles",
    backtestPeriod: "2022–2026 (4.2 years)",
    allYearsProfitable: true,
    status: "Paper Trading (since Mar 7, 2026)",
    recommendedCapital: "$100,000+ per coin",
    stats: {
      winRate: "98.5–99.3%",
      sharpe: "1.45–2.27 (avg 1.72)",
      maxDrawdown: "4.2–9.0%",
      profitFactor: "4.21–12.99",
      totalTrades: "~30,200",
    },
    perCoin: [
      { coin: "DOGE", totalReturn: "—", maxDD: "—", sharpe: "2.27", winRate: "99.0%", profitFactor: "—" },
      { coin: "ADA", totalReturn: "—", maxDD: "4.2%", sharpe: "1.84", winRate: "98.5%", profitFactor: "—" },
      { coin: "XRP", totalReturn: "—", maxDD: "—", sharpe: "1.58", winRate: "99.3%", profitFactor: "—" },
      { coin: "ETH", totalReturn: "—", maxDD: "—", sharpe: "1.47", winRate: "98.8%", profitFactor: "—" },
      { coin: "SOL", totalReturn: "—", maxDD: "—", sharpe: "1.45", winRate: "99.1%", profitFactor: "11.55" },
    ],
    liveData: {
      pnl30d: "—",
      trades30d: "—",
      amountTrading: "—",
      minFunds: "$100,000 / 1 BTC",
    },
    backtestBars: [
      { label: "50m (4.2yr)", value: "+421%",  barPercent: 95 },
      { label: "12m",         value: "+30%",   barPercent: 35 },
      { label: "6m",          value: "+14%",   barPercent: 20 },
      { label: "3m",          value: "+8%",    barPercent: 12 },
    ],
    media: {
      explainer: "https://kwtagyeqhdxswpztqcsa.supabase.co/storage/v1/object/public/data-room/media/sigma-2x-explainer.mp4",
      pitch: "https://kwtagyeqhdxswpztqcsa.supabase.co/storage/v1/object/public/data-room/media/sigma-2x-pitch.pdf",
    },
    safetyLayers: [
      { name: "Direction-specific stop-losses", desc: "Separate thresholds for long and short sides" },
      { name: "Regime detection", desc: "Higher-timeframe market structure determines direction" },
      { name: "Liquidation buffer", desc: "Stop-losses fire 10–12x before liquidation distance" },
      { name: "Circuit breakers", desc: "Progressive halt on daily/weekly/monthly losses" },
      { name: "Manual kill switch", desc: "Instant shutdown from the dashboard" },
    ],
  },
  "both": {
    id: "both",
    name: "Compare: 1x vs 2x",
    tagline: "Side-by-Side — Spot vs Derivatives",
    description:
      "A direct comparison of both Sigma strategies. See how the conservative spot approach (1x) and the leveraged derivatives strategy (2x) complement each other in a diversified portfolio.",
    type: "Comparison",
    direction: "Long only (1x) + Bidirectional (2x)",
    leverage: "None (1x) / 2x isolated (2x)",
    market: "Spot + Derivatives",
    liquidationRisk: "Zero (1x) / Zero in backtest (2x)",
    coins: ["DOGE", "ADA", "XRP", "ETH", "SOL"],
    timeframe: "1-hour candles",
    backtestPeriod: "2019–2026",
    allYearsProfitable: true,
    status: "Paper Trading (since Mar 7, 2026)",
    recommendedCapital: "$10,000+ (1x) / $100,000+ (2x)",
    stats: {
      winRate: "94–99%",
      sharpe: "1.45–3.31",
      maxDrawdown: "2.8–9.0%",
      profitFactor: "2.26–12.99",
      totalTrades: "~55,000+",
    },
    perCoin: [
      { coin: "DOGE", totalReturn: "+228.6% (1x)", maxDD: "2.8% (1x)", sharpe: "2.59 / 2.27", winRate: "97.1% / 99.0%", profitFactor: "3.72" },
      { coin: "ADA", totalReturn: "+211.1% (1x)", maxDD: "6.9% / 4.2%", sharpe: "2.81 / 1.84", winRate: "98.2% / 98.5%", profitFactor: "5.27" },
      { coin: "XRP", totalReturn: "+265.4% (1x)", maxDD: "3.2%", sharpe: "3.31 / 1.58", winRate: "99.4% / 99.3%", profitFactor: "7.45" },
      { coin: "ETH", totalReturn: "+88.3% (1x)", maxDD: "3.7%", sharpe: "2.41 / 1.47", winRate: "94.4% / 98.8%", profitFactor: "2.26" },
      { coin: "SOL", totalReturn: "+115.8% (1x)", maxDD: "3.2%", sharpe: "2.95 / 1.45", winRate: "96.3% / 99.1%", profitFactor: "2.71 / 11.55" },
    ],
    liveData: {
      pnl30d: "—",
      trades30d: "—",
      amountTrading: "—",
      minFunds: "$10,000+ / $100,000+",
    },
    backtestBars: [
      { label: "Sigma 1x (6.7yr)", value: "+265.4%", barPercent: 63 },
      { label: "Sigma 2x (4.2yr)", value: "+421%",   barPercent: 95 },
      { label: "Sigma 1x (12m)",    value: "+42.5%",   barPercent: 35 },
      { label: "Sigma 2x (12m)",    value: "+30%",     barPercent: 25 },
    ],
    media: {
      explainer: "https://kwtagyeqhdxswpztqcsa.supabase.co/storage/v1/object/public/data-room/media/compare-explainer.mp4",
      pitch: "https://kwtagyeqhdxswpztqcsa.supabase.co/storage/v1/object/public/data-room/media/compare-pitch.pdf",
    },
    safetyLayers: [
      { name: "Per-trade stop-loss", desc: "Hard maximum loss on every trade (both strategies)" },
      { name: "Multi-confirmation entry", desc: "4-confirmation (1x) + regime detection (2x)" },
      { name: "Capital limits", desc: "Reserve always held back; diversified across coins" },
      { name: "Circuit breakers", desc: "Auto-reduce → pause → full halt on losses" },
      { name: "Manual kill switch", desc: "Instant shutdown from the dashboard" },
    ],
  },
} as const;

export type StrategyKey = keyof typeof strategies;
